version: "3.7"
services:
  backend:
    image: swag-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  frontend:
    image: swag-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
  matcher-ai:
    image: swag-matcher-ai
    build:
      context: matcher-ai
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
